
INFO:     Will watch for changes in these directories: ['/home/serkan/fastingapi']
INFO:     Uvicorn running on http://0.0.0.0:9800 (Press CTRL+C to quit)
INFO:     Started reloader process [2320787] using statreload
INFO:     Started server process [2320814]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:34386 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:34386 - "GET /openapi.json HTTP/1.1" 200 OK
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2320814]
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 4
    from
        ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
Process SpawnProcess-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 4
    from zoneinfo
                ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
Process SpawnProcess-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 4
    from zoneinfo import
                        ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
Process SpawnProcess-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 4, in <module>
    from zoneinfo import Zone
ModuleNotFoundError: No module named 'zoneinfo'
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
Process SpawnProcess-6:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 4, in <module>
    from zoneinfo import ZoneInfo
ModuleNotFoundError: No module named 'zoneinfo'
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
Process SpawnProcess-7:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 4, in <module>
    from zoneinfo import ZoneInfo
ModuleNotFoundError: No module named 'zoneinfo'
WARNING:  StatReload detected file change in 'lib/python3.9/site-packages/sqlalchemy/processors.py'. Reloading...
Process SpawnProcess-8:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 4, in <module>
    from zoneinfo import ZoneInfo
ModuleNotFoundError: No module named 'zoneinfo'
WARNING:  StatReload detected file change in 'lib/python3.9/site-packages/sqlalchemy/processors.py'. Reloading...
Process SpawnProcess-9:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 4, in <module>
    from zoneinfo import ZoneInfo
ModuleNotFoundError: No module named 'zoneinfo'
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
Process SpawnProcess-10:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 4, in <module>
    from pytz import ZoneInfo
ImportError: cannot import name 'ZoneInfo' from 'pytz' (/usr/lib/python3/dist-packages/pytz/__init__.py)
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
Process SpawnProcess-11:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 4, in <module>
    from pytz import ZoneInfo
ImportError: cannot import name 'ZoneInfo' from 'pytz' (/usr/lib/python3/dist-packages/pytz/__init__.py)
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
Process SpawnProcess-12:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 4, in <module>
    from pytz import ZoneInfo
ImportError: cannot import name 'ZoneInfo' from 'pytz' (/usr/lib/python3/dist-packages/pytz/__init__.py)
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
Process SpawnProcess-13:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 4, in <module>
    from pytz import ZoneInfo
ImportError: cannot import name 'ZoneInfo' from 'pytz' (/usr/lib/python3/dist-packages/pytz/__init__.py)
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
Process SpawnProcess-14:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 4, in <module>
    from pytz import ZoneInfo
ImportError: cannot import name 'ZoneInfo' from 'pytz' (/usr/lib/python3/dist-packages/pytz/__init__.py)
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
Process SpawnProcess-15:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 4, in <module>
    from pytz import ZoneInfo
ImportError: cannot import name 'ZoneInfo' from 'pytz' (/usr/lib/python3/dist-packages/pytz/__init__.py)
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Started server process [2336054]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2336054]
INFO:     Started server process [2336091]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2336091]
INFO:     Started server process [2336342]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2336342]
INFO:     Started server process [2336349]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2336349]
INFO:     Started server process [2336385]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2336385]
INFO:     Started server process [2336425]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2336425]
INFO:     Started server process [2336531]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:36572 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:36572 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:36574 - "POST /fast/1/fasts/ HTTP/1.1" 400 Bad Request
INFO:     127.0.0.1:47126 - "POST /fast/1/end_fast/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:47834 - "POST /fast/1/fasts/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:49736 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.73:61511 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.73:61511 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     192.168.178.88:52736 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:52908 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:52978 - "GET /users/1 HTTP/1.1" 200 OK
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2336531]
INFO:     Started server process [2717282]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     192.168.178.88:53636 - "GET /users/1 HTTP/1.1" 200 OK
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2717282]
INFO:     Started server process [2719301]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2719301]
Process SpawnProcess-25:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 8, in <module>
    from ..database.database import DBUser
  File "/home/serkan/fastingapi/database/database.py", line 54
    if
      ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
Process SpawnProcess-26:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 8, in <module>
    from ..database.database import DBUser
  File "/home/serkan/fastingapi/database/database.py", line 54
    if __n
         ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
Process SpawnProcess-27:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 8, in <module>
    from ..database.database import DBUser
  File "/home/serkan/fastingapi/database/database.py", line 54
    if __n
         ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
Process SpawnProcess-28:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 8, in <module>
    from ..database.database import DBUser
  File "/home/serkan/fastingapi/database/database.py", line 54
    if __name__ == ''
                    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
Process SpawnProcess-29:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 8, in <module>
    from ..database.database import DBUser
  File "/home/serkan/fastingapi/database/database.py", line 54
    if __name__ == '__main__'
                            ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
Process SpawnProcess-30:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 8, in <module>
    from ..database.database import DBUser
  File "/home/serkan/fastingapi/database/database.py", line 55
    
    ^
SyntaxError: unexpected EOF while parsing
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
INFO:     Started server process [2719651]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2719651]
Process SpawnProcess-32:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 8, in <module>
    from ..database.database import DBUser
  File "/home/serkan/fastingapi/database/database.py", line 55
    session.
           ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
INFO:     Started server process [2719839]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2719839]
INFO:     Started server process [2719867]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2719867]
INFO:     Started server process [2719901]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2719901]
INFO:     Started server process [2719953]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2719953]
INFO:     Started server process [2719961]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2719961]
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
INFO:     Started server process [2719982]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2719982]
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
INFO:     Started server process [2720059]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2720059]
INFO:     Started server process [2720426]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2720426]
INFO:     Started server process [2720460]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2720460]
INFO:     Started server process [2720733]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2720733]
INFO:     Started server process [2720809]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2720809]
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
INFO:     Started server process [2720868]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'database/database.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2720868]
INFO:     Started server process [2720989]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2720989]
Process SpawnProcess-49:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 6, in <module>
    from .fastapi import Depends, APIRouter, HTTPException
ModuleNotFoundError: No module named 'fastingapi.modules.fastapi'
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
INFO:     Started server process [2721766]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2721766]
Process SpawnProcess-51:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 6, in <module>
    from . import Depends, APIRouter, HTTPException
ImportError: cannot import name 'Depends' from 'fastingapi.modules' (/home/serkan/fastingapi/modules/__init__.py)
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-52:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 6
    from  import Depends, APIRouter, HTTPException
          ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
INFO:     Started server process [2721882]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2721882]
INFO:     Started server process [2722184]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2722184]
Process SpawnProcess-55:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 53
    user.
        ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
INFO:     Started server process [2722217]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2722217]
INFO:     Started server process [2722244]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2722244]
INFO:     Started server process [2722358]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2722358]
INFO:     Started server process [2722367]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
<fastingapi.database.database.DBUser object at 0x7f0e2a3d16a0>
INFO:     192.168.178.88:57348 - "GET /users/1 HTTP/1.1" 200 OK
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2722367]
INFO:     Started server process [2722740]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
[<fastingapi.database.database.DBFast object at 0x7fa0a52ccca0>, <fastingapi.database.database.DBFast object at 0x7fa0a52ccb20>, <fastingapi.database.database.DBFast object at 0x7fa0a52b43d0>]
INFO:     192.168.178.88:57514 - "GET /users/1 HTTP/1.1" 200 OK
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2722740]
Process SpawnProcess-61:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 99
    return db_user
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-62:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 100
    return db_user
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-63:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 100
    return db_user
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-64:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 90
    """
"""
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-65:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 90
    """Get list of all users.
"""
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-66:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 100
    return db_user
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-67:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 99
    return db_user
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-68:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 91
    """Get list of all users.
"""
    ^
IndentationError: expected an indented block
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-69:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 91
    """Get list of all users.
"""
    ^
IndentationError: expected an indented block
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-70:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 101
    return db_user
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-71:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 101
    return db_user
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-72:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 101
    return db_user
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-73:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 102
    return db_user
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-74:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 103
    return db_user
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-75:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 103
    return db_user
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-76:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 105
    return db_user
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-77:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 105
    return db_user
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-78:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 105
    return db_user
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-79:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 105
    return db_user
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-80:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 104
    return db_user
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
Process SpawnProcess-81:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 104
    return db_user
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
WARNING:  StatReload detected file change in 'modules/users.py'. Reloading...
INFO:     Started server process [2724461]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     192.168.178.88:59714 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:33026 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:34064 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:35098 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:36574 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:36750 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:36944 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:37156 - "GET /users/1 HTTP/1.1" 200 OK
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2724461]
Process SpawnProcess-84:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 51
    def future_date(cls, dt):
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Started server process [2731518]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     192.168.178.88:37342 - "GET /users/1 HTTP/1.1" 200 OK
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2731518]
Process SpawnProcess-86:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 51
    def future_date(cls, dt):
    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Started server process [2731667]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2731667]
INFO:     Started server process [2731771]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2731771]
Process SpawnProcess-89:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 82
    if
      ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
Process SpawnProcess-90:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 82
    if fast.end_time
                    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
Process SpawnProcess-91:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 83
    active_fast.end_time = fast.end_time
    ^
IndentationError: expected an indented block
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Started server process [2731959]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     192.168.178.88:37602 - "GET /users/1 HTTP/1.1" 200 OK
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2731959]
Process SpawnProcess-93:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 86
    active_fast.completed = True
    ^
IndentationError: expected an indented block
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Started server process [2732070]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2732070]
INFO:     Started server process [2732127]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2732127]
INFO:     Started server process [2732185]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2732185]
INFO:     Started server process [2732318]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2732318]
INFO:     Started server process [2732400]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     192.168.178.88:37774 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:37950 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:38082 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:38190 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:38380 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:38480 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:38590 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:38704 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:38812 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:39008 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:39110 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:39216 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:39338 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:39448 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:39654 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:39746 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:39852 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:39980 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:40092 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:40288 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:40404 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:40506 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:40608 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:40746 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:40936 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:41044 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:41140 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:41298 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:41392 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:41582 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:41708 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:41806 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:41898 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:42034 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:42222 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:42314 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:42430 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:42528 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:42650 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:42822 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:42942 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:43056 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:43152 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:43272 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:43460 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:43560 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:43668 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:43780 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:43902 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:44084 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:44192 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:44290 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:44404 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:44514 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:44740 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:44846 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:44954 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:45066 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:45184 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:45370 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:45474 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:45570 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:45686 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:45798 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:46010 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:46098 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:46210 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:46316 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:46424 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:46626 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:46730 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:46834 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:46950 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:47076 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:47266 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:47360 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:47468 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:47566 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:47694 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:47878 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:47970 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:48082 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:48188 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:48316 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:48510 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:48608 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:48716 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:48820 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:48930 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:49134 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:49240 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:49338 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:49434 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:49574 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:49762 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:49850 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:49968 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:50066 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:50190 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:50376 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:50480 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:50578 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:50686 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:50812 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:51006 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:51102 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:51204 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:51304 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:51426 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:51612 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:51722 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:51822 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:51936 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:52068 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:52296 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:52398 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:52502 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:52604 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:52724 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:52914 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:53020 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:53124 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:53228 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:53354 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:53544 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:53656 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:53760 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:53858 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:53978 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:54162 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:54270 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:54374 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:54480 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:54604 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:54792 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:54902 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:55004 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:55110 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:55242 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:55424 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:55534 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:55634 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:55736 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:55858 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:56048 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:56152 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:56262 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:56386 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:56504 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:56690 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:56794 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:56900 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:57004 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:57132 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:57320 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:57420 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:57536 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:57634 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:57754 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:57938 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:58040 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:58146 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:58252 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:58358 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:58560 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:58660 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:58768 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:58876 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:58982 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:59184 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:59292 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:59394 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:59500 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:59612 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:59846 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:59944 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:60052 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:60164 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:60268 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:60466 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:60576 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:60676 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:60782 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:60892 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:32860 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:32970 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:33084 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:33188 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:33300 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:33498 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:33600 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:33704 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:33810 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:33920 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:34124 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:34224 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:34330 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:34430 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:34546 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:34752 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:34858 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:34964 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:35068 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:35180 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:35384 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:35482 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:35586 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:35716 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:35830 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:36040 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:36148 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:36250 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:36356 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:36466 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:36676 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:36794 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:36900 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:37008 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:37126 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:37336 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:37450 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:37560 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:37676 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:37788 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:37996 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:38098 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:38204 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:38310 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:38418 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:38620 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:38736 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:38844 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:38950 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:39066 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:39300 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:39404 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:39510 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:39618 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:39724 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:39928 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:40046 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:40146 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:40254 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:40364 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:40568 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:40676 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:40780 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:40880 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:40988 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:41192 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:41298 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:41406 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:41512 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:41620 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:41824 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:41924 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:42030 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:42130 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:42250 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:42446 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:42554 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:42662 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:42764 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:42902 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:43120 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:43240 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:43368 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:43510 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:43632 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:43846 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:43968 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:44092 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:44220 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:44346 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:44566 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:44682 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:44804 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:44922 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:45044 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:45268 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:45386 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:45510 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:45642 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:45768 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:45986 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:46230 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:46464 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:46670 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:46870 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:47172 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:47366 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:47556 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:47756 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:47960 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:48290 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:48488 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:48684 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:48886 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:49088 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:49382 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:49570 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:49760 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:49968 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:50184 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:50472 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:50700 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:50900 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:51098 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:51302 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:51588 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:51834 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:52034 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:52222 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:52422 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:52698 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:52900 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:53090 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:53274 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:53472 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:53744 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:53962 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:54144 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:54322 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:54514 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:54796 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:55030 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:55240 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:55452 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.73:56085 - "GET / HTTP/1.1" 200 OK
INFO:     192.168.178.88:55646 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.73:56087 - "GET /docs HTTP/1.1" 200 OK
INFO:     192.168.178.73:56087 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     192.168.178.73:56114 - "POST /fast/1/end_fast/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 364, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/serkan/.local/lib/python3.8/site-packages/fastapi/applications.py", line 212, in __call__
    await super().__call__(scope, receive, send)
  File "/home/serkan/.local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/serkan/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/serkan/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/serkan/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/serkan/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/serkan/.local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/serkan/.local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/serkan/.local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/serkan/.local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/home/serkan/.local/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/serkan/.local/lib/python3.8/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/serkan/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/serkan/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/serkan/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/home/serkan/fastingapi/modules/fasts.py", line 118, in end_fast_for_user
    if fast.end_time < active_fast.start_time:
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
INFO:     192.168.178.88:55928 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:56144 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:56332 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.73:56140 - "POST /fast/1/end_fast/ HTTP/1.1" 422 Unprocessable Entity
INFO:     192.168.178.73:56142 - "POST /fast/1/end_fast/ HTTP/1.1" 200 OK
INFO:     192.168.178.88:56530 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:57734 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:58078 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:58194 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:58272 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:58434 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:58618 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:58816 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:59018 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:59264 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:59502 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:59710 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:59840 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:59994 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:60160 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:60370 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:60580 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:60792 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:32812 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:33070 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:33282 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:33480 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:33842 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.73:54832 - "POST /fast/1/fasts/ HTTP/1.1" 200 OK
INFO:     192.168.178.88:34232 - "GET /users/1 HTTP/1.1" 200 OK
INFO:     192.168.178.88:34538 - "GET /users/1 HTTP/1.1" 200 OK
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2732400]
Process SpawnProcess-99:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 17, in <module>
    class FastCreate(FastBase):
  File "/home/serkan/fastingapi/modules/fasts.py", line 24, in FastCreate
    planned_end_time: Optional[datetime] = start_time + timedelta(hours=23)
NameError: name 'start_time' is not defined
WARNING:  StatReload detected file change in 'modules/fasts.py'. Reloading...
Process SpawnProcess-100:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/serkan/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serkan/fastingapi/./main.py", line 17, in <module>
    from fastingapi.modules import users, fasts, weights
  File "/home/serkan/fastingapi/modules/users.py", line 9, in <module>
    from ..modules import fasts, weights
  File "/home/serkan/fastingapi/modules/fasts.py", line 17, in <module>
    class FastCreate(FastBase):
  File "/home/serkan/fastingapi/modules/fasts.py", line 24, in FastCreate
    planned_end_time: Optional[datetime] = start_time + timedelta(hours=23)
NameError: name 'start_time' is not defined
